### ISSUE TITLE
Thumbnail photo

### ISSUE THREAD

**Issue by RicardoDMelo** [dbaq/cordova-plugin-contacts-phone-numbers#11]
I know this is meant to be a light plugin, but we have not a way to retreive contact photos. 
I will make this feature for my project, if you want, i can pull it.

**Comment by dbaq** [comment]
hey @ricksmelo, that would be great to have this feature if it does not impact the performances (on android at least). And it would be awesome if it could be an option too.

thank you for contributing anyway :beers:

**Comment by dbaq** [comment]
any updates @ricksmelo?

**Comment by ricksmelo** [comment]
So @dbaq, I did the feature, but, by now, is very simple. I only added a attribute in the object contact, labeled "thumbnailPhoto". It's a url string pointing to the android directory, virtual or not, where the photo is stored. If no photo is found, it returns a empty value. I didn't test the times, but it's still fast, on my Nexus 5 with ~110 contacts. I want to make a option, but I'm still working. If you want, I can already make a pull request :)

PS: sorry for bad english, not my first language.

**Comment by dbaq** [comment]
No rush, thank you for working on it. 

You said: ```It's a url string pointing to the android directory```

So that means we need to add an extra permission to access the file storage? How are you displaying the file in the UI?

**Comment by ricksmelo** [comment]
I guess not, at least I didn't add anymore permissions. Url comes like this: "content://com.android.contacts/contacts/739/photo".

If we put in a img src, android makes the work for us, like this: 
<img src="content://com.android.contacts/contacts/739/photo"/>.

The only thing that we might pay attention when working with this is the default sanitization, who adds "unsafe:" at the beginning of the url. on app.js we need to configure what types of protocols can be used: 

.config(['$compileProvider', function($compileProvider) {
    $compileProvider.imgSrcSanitizationWhitelist(/^\s*(https?|ftp|file|blob|content|data):|data:image\//);
}])

Besides that, no more worries.

**Comment by dbaq** [comment]
I like that!

Have you thought about supporting iOS?

**Comment by ricksmelo** [comment]
Well, I never worked with iOS platforms, but I want to. Windows Phone is C#, isn't it?

**Comment by dbaq** [comment]
yes or visual basic, it would be nice to have the iOS support in the PR.

**Comment by ricksmelo** [comment]
Well, I'll give a look at the language, maybe I can do something. Knowledge is never too much

**Comment by philecom** [comment]
@ricksmelo Please can you paste your code for some of us to follow. I have tried but still cannot get the photo to show.

**Comment by natanraj** [comment]
it is an awesome one Ricksmelo. I am not a developer (android or iOS). But can do a little bit on Js/Html. Could we add a filter like mobileNumber starting with some XYZ etc. (WIll add some flexibility for developers) ... I assume Cordova takes an arguments as one of its parameter on exec. Can we pass it ? I assume cr.query may need one extra condition in ContactsManager.java. But as i said i have been searching for this plugin for last 3 days. Thanks once again.

**Comment by dbaq** [comment]
@natanraj for feature request, open another issue thanks.

**Comment by dbaq** [comment]
Closing this one since #44 has been merged.

**Comment by dbaq** [comment]
I released a new version on npm https://www.npmjs.com/package/cordova-plugin-contacts-phonenumbers (v0.0.9)
