### ISSUE TITLE
Unable to use this plugin in Intel XDK

### ISSUE THREAD

**Issue by SamarRizvi** [dbaq/cordova-plugin-contacts-phone-numbers#12]
I am trying to add this plugin in Intel XDK thrid-party plugins. I have given plugin id at com.dbaq.cordova.contactsPhoneNumbers and Repo URl as https://github.com/dbaq/cordova-plugin-contacts-phone-numbers.git but even after bulding the whole project for android, when I use navigator.contactsPhoneNumbers.list after deviceReady event, I get "Cannot read property 'list' of undefined". Is there anything, I am missing. The Cordova CLI version is 4.1.2

Note that, I have tested the build on android phone but still no success.

**Comment by dbaq** [comment]
Hey @SamarRizvi,

Sorry for the response time. It looks like the plugin is not imported correctly. I never used the Intel XDK. Have you read https://software.intel.com/en-us/xdk/docs/adding-third-party-plugins-to-your-xdk-cordova-app

**Comment by SamarRizvi** [comment]
Hi @dbaq ,

I have imported other plugins that are on github, they work fine. Do not understand, why your plugin doesn't work, even when Intel XDK shows your plugin as installed after build.

**Comment by dbaq** [comment]
Can you share some code? Which platform are you using?

**Comment by SamarRizvi** [comment]
Sorry for replying late. I am using Intel XDK and using html5+cordova. About sharing code, you first have to download Intel XDK, and then create a new html5+cordova project or use a sample html5+cordova project that they have. Then include your plugin as third party plugin in your project ( read "Including Third Party Plugin" section at https://software.intel.com/en-us/xdk/docs/adding-third-party-plugins-to-your-xdk-cordova-app). Then use your example code after deviceReady. You have to build the project for a third party plugin to work and deploy the apk on your mobile phone to check if it's working. I have already repeated the above steps over and over again, but no use. Note that the cordova CLI version that I have set in Intel XDK is 4.1.2. All third party plugins work fine on mobile, but navigator.contactsPhoneNumbers always comes undefined.

**Comment by dbaq** [comment]
hey @SamarRizvi,

It is working for me when I test on my android device. You have to use the APK coming from the build, do not use their App preview:

![screen shot 2015-06-29 at 5 39 49 pm](https://cloud.githubusercontent.com/assets/1867703/8422032/2fe0e70e-1e8b-11e5-9c57-cad4f98af9ae.png)

Here is my ```onDeviceReady``` function that I used in main.js:
```
var onDeviceReady=function(){
    alert(device.model);
    navigator.contactsPhoneNumbers.list(function(contacts) {
      alert(contacts.length + ' contacts found');
   }, function(error) {
      alert(error);
   });
   if( window.Cordova && navigator.splashscreen ) {     // Cordova API detected
        navigator.splashscreen.hide() ;                 // hide splash screen
    }
};
```

also in index.html, make sure to have the cordova.js imported before main.js:

```
<script type="text/javascript" src="cordova.js"></script>
<script src="js/main.js" type="text/javascript"></script>
```

![phone](https://lh3.googleusercontent.com/4-BlF_jD6AUIps2L38kXDaYgKIEMrtoUd-YeFWxX1gNq)


I am closing this issue since it is not related to this plugin. Do not hesitate to contact the XDK team if you can't figure it out what is going on.

**Comment by robertlight** [comment]
I am also getting navigator.contactsPhoneNumbers as undefined, I get "Cannot read property 'list' of undefined"

I am using phonegap and running inside of intelliJ using "serve android"
