### ISSUE TITLE
Third Party Plugin - phonegap

### ISSUE THREAD

**Issue by natanraj** [dbaq/cordova-plugin-contacts-phone-numbers#14]
Will this plugin be available on Phone Gap Third Party Plugins any time ?

**Comment by dbaq** [comment]
Hi @natanraj,

This plugin won't be available on PhoneGap build because a paid account is required for open source developers to be able to publish plugins.

```Phonegap build: There was recently a policy change so if you are not a paid subscriber, you can't submit plugins.```

Sorry.

**Comment by natanraj** [comment]
Your plugin is a very useful Plugin, particularly for Android.. I am willing to pay for it (i assume it is $9.99  per month on PhoneGap).. let us know if we can collaboratively work into this.

**Comment by natanraj** [comment]
hi DBAQ, Hope you are enjoying your vacation. Once you are back, please let us if I can upload your plugin on your behalf to Phonegap Plugman.

**Comment by dbaq** [comment]
@natanraj what do you need me to do to be able to push this plugin?

**Comment by natanraj** [comment]
May I have your email Tirupur discuss further?

**Comment by dbaq** [comment]
Sure, you can find all my contact information, there http://didierbaquier.fr/

**Comment by dbaq** [comment]
Since the PhoneGap Plugins directory is being deprecated on October 15h, 2015, this plugin will soon be listed in the new Cordova Plugin NPM directory at http://plugins.cordova.io/npm/index.html

**Comment by dbaq** [comment]
Done http://plugins.cordova.io/npm/index.html?q=cordova-plugin-contacts-phonenumbers.
