### ISSUE TITLE
fetching contacts in batches

### ISSUE THREAD

**Issue by prakashsejwani** [dbaq/cordova-plugin-contacts-phone-numbers#15]
Hi @dbaq ,

Your plugin works great for me. However, I had one request - I noticed that it takes an average of 10 secs or more to pick an entire contacts list (ranging from 700 stored contacts to 1400 stored contacts). 10 seconds is too long a wait in my opinion so can you help me with - fetching contacts in batches, where your plugin fetches contacts in batches - either by no. of contacts (i.e., 100 at a time) or by alphabet (i.e, all contacts starting with ‘a’ first, then starting with ‘b’ and so on)

**Comment by dbaq** [comment]
If we go with the alphabet solution, it could also solve this issue https://github.com/dbaq/cordova-plugin-contacts-phone-numbers/issues/13.

**Comment by dbaq** [comment]
@prakashsejwani, i am curious to know if you have tried to retrieve the contacts list with the official cordova plugin, and if yes, what are the performances?

**Comment by prakashsejwani** [comment]
@dbaq, yes i have tried it and i found yours is better in terms of performance than that, because it takes more time as it fetches all contacts, and i wanted only phoneNumbers one.

**Comment by dbaq** [comment]
Glad to hear that, I have plenty of work right now and I am leaving soon for a 2 weeks vacation so I will probably have time to work on it in 4 weeks. Probably not before.

**Comment by dbaq** [comment]
After looking at the code and the possibilities, I will implement a method to filter the contact list. For instance you will be able to retrieve all the contacts starting by A or B. So please, follow the development in #13.
