### ISSUE TITLE
How to use this plugin ?

### ISSUE THREAD

**Issue by abhishekdeshkar** [dbaq/cordova-plugin-contacts-phone-numbers#16]
Respected sir,

How do I use this plugin on PhoneGap ? I have installed the plugin in phonegap. Do I need to define .js file ? And where should I write this code? Here is my code : 

document.addEventListener("deviceready", onDeviceReady, false);

        function onDeviceReady()
        {
		    navigator.contactsPhoneNumbers.list(function(contacts) {
		      alert(contacts.length + ' contacts found');
		      for(var i = 0; i < contacts.length; i++) {
		         console.log(contacts[i].id + " - " + contacts[i].displayName);
		         for(var j = 0; j < contacts[i].phoneNumbers.length; j++) {
		            var phone = contacts[i].phoneNumbers[j];
		            console.log("===> " + phone.type + "  " + phone.number + " (" + phone.normalizedNumber+ ")"); 
		         }
		      }
		   }, function(error) {
		      console.error(error);
		   });
        }
        
Is this correct ? Thanks!

**Comment by dbaq** [comment]
This plugin is not yet available for phonegap but you can use it with cordova. See #14 for more information.

**Comment by abhishekdeshkar** [comment]
Can you please make it for phonegap ? It takes too much time to load numbers in phonegap. I request you to make one :+1:
