### ISSUE TITLE
Add to Cordova Plugins registry (npm)

### ISSUE THREAD

**Issue by martin-eq** [dbaq/cordova-plugin-contacts-phone-numbers#20]
Please, could you add this plugin to the Cordova Plugins registry so I can install it using PhoneGap Cloud Build system?

https://cordova.apache.org/plugins/

Thanks in advance.

**Comment by dbaq** [comment]
yes, will be done by tomorrow max.

**Comment by martin-eq** [comment]
Wow, ultra fast response!
Thanks a lot for the effort in building this plugin that mitigates a lot of issues I had to retrieve contacts with Cordova's contacts plugin.

**Comment by dbaq** [comment]
Hey @martin-eq,

the plugin is on NPM: https://www.npmjs.com/package/cordova-plugin-contacts-phonenumbers and I added it to Cordova plugins registry: https://cordova.apache.org/plugins/?q=cordova-plugin-contacts-phonenumbers

Let me know if you need anything else.

Cheers.
