### ISSUE TITLE
build on cordova-ios 4.0.1 failed

### ISSUE THREAD

**Issue by bastian-meier** [dbaq/cordova-plugin-contacts-phone-numbers#24]
I am using phonegapbuild and wanted to update to ios cordova version 4.0.1

The Build log shows this error:

```
The following build commands failed:
	CompileC build/Jabbit.build/Release-iphoneos/Jabbit.build/Objects-normal/armv7/CDVContactsPhoneNumbers.o Jabbit/Plugins/com.dbaq.cordova.contactsPhoneNumbers/CDVContactsPhoneNumbers.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

**Comment by dbaq** [comment]
hey @bastian-meier,

Can you please provider more information. The plugin is building correctly for iOS. If it is an issue with phonegapbuild, you should contact them directly.

**Comment by dbaq** [comment]
Closing this one since no updates. Feel free to reopen it.
