### ISSUE TITLE
navigator.contactsPhoneNumbers is undefined

### ISSUE THREAD

**Issue by robertlight** [dbaq/cordova-plugin-contacts-phone-numbers#27]
I have the plugin installed (as per the docs)

but navigator.contactsPhoneNumbers is showing up undefined in my javascript.

any ideas?

**Comment by malek75** [comment]
Hi!

You can use navigator.contactsPhoneNumbers only after device is ready : 

```
document.addEventListener("deviceready", function() {
    navigator.contactsPhoneNumbers.list(function(contacts) {  
        //do something
    }, function(error) {
          //do something
    });
}, false);
```

**Comment by robertlight** [comment]
I started with the basic hello-world app:
$ phonegap create myApp
$ phonegap build android
$ phonegap plugin add https://github.com/dbaq/cordova-plugin-contacts-phone-numbers.git
$ phonegap build android
I kept getting a compile error which went away when I did the following:
$ phonegap platform update android@5.0.0      
$ phonegap build android
..this worked
$ phonegap serve android

but now navigator.contactsPhoneNumber is undefined after deviceready....

**Comment by robertlight** [comment]
I thought maybe it was that I was using the github version so I did the following:

$ phonegap plugin rm com.dbaq.cordova.contactsPhoneNumbers
$ phonegap plugin add cordova-plugin-contacts-phonenumbers
$ phonegap build android

...but alas... navigator.contactsPhoneNumbers was still undefined. (note my use of the non-plural form in my previous note was a editor's error... I've been using the right code "navigator.contactsPhoneNumbers" properly.

**Comment by robertlight** [comment]
[myApp.zip](https://github.com/dbaq/cordova-plugin-contacts-phone-numbers/files/162345/myApp.zip)

above is my entire tree - perhaps you can find the boneheaded thing I did wrong.

**Comment by malek75** [comment]
The best way to with plugins app is :

phonegap create app
phonegap platform add android
phonegap plugin add my-plugin
phonegap build android
phonegap run android

NOT WITH SERVE

**Comment by robertlight** [comment]
I figured out some of the problems:
1) instead of "phonegap create app".... you have to do  "phonegap create com.app"
2) need to edit config.xml and change:
         <icon src="icon.png" />
    to:
         <icon src="www/icon.png" />

3) Instead of "phonegap platform add android" you have to use "phonegap platform add android@5.0.0"

It now works using "phonegap run android"

but NOT "phonegap serve android" where navigator.contactsPhoneNumbers is undefined.

Any ideas on how I can test on my actual device?

**Comment by dbaq** [comment]
still having the issue? i'll recommend you to do not use phonegap but cordova directly.

**Comment by dbaq** [comment]
Closing this one.
