### ISSUE TITLE
Build error on android with cordova 5

### ISSUE THREAD

**Issue by johnnyoin** [dbaq/cordova-plugin-contacts-phone-numbers#28]
Hi,
When building my project for android I get the following error:
`cannot find symbol: cordova.hasPermission(string)`
Anyone has a hint about this ?

**Comment by dbaq** [comment]
probably a regression due to this PR: https://github.com/dbaq/cordova-plugin-contacts-phone-numbers/pull/26

will look at it

**Comment by dbaq** [comment]
Hello @johnnyoin,

which `android:targetSdkVersion` do you have in your `AndroidManifest.xml` file? I just tried on my phone and it worked perfectly. Here is what I have:
`<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23" />`

**Comment by johnnyoin** [comment]
Hi @dbaq,

I have: `<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" />`

**Comment by kevin-mills** [comment]
I am experiencing the same problem on compilation. Setting version as above does not resolve.

**Comment by dbaq** [comment]
Hey guys, I tried again with cordova 5.0.0, 6.0.0, I cannot reproduce. `$ cordova build android` works for me. Are you sure you got the latest version?

You can make sure via
`$ cordova plugin rm com.dbaq.cordova.contactsPhoneNumbers`
`$ cordova plugin add https://github.com/dbaq/cordova-plugin-contacts-phone-numbers.git`

can you guys give me more information so I can reproduce?

thanks

**Comment by johnnyoin** [comment]
Alright I got it, the problem was the version of cordova-android.
Running `cordova platform update android@5.1.1` did the trick.

**Comment by kevin-mills** [comment]
Thanks guys upgrading cordova version worked for me too.

**Comment by dbaq** [comment]
Good job @johnnyoin for figuring this out! :+1:
