### ISSUE TITLE
CDVContactsPhoneNumbers.m:22:9 'Cordova/NSArray+Comparisons.h' file not found

### ISSUE THREAD

**Issue by shikarkhane** [dbaq/cordova-plugin-contacts-phone-numbers#29]
On xcode, archive build fails with error 
`CDVContactsPhoneNumbers.m:22:9 'Cordova/NSArray+Comparisons.h' file not found`

Xcode version - Version 7.2.1 (7C1002)
Cordova-Ios - 4.1.0
Cordova version - 6.0.0
com.dbaq.cordova.contactsPhoneNumbers" spec="~0.0.6" ( installed via nam and direct git also)

Archive build succeeds, if i remove this plugin.

**Comment by dbaq** [comment]
Thanks for the report @shikarkhane, I pushed a commit on master, it should be fine now. I will publish a new release soon.

**Comment by shikarkhane** [comment]
Works now. Cheers
