### ISSUE TITLE
Please add Typescript definition file 

### ISSUE THREAD

**Issue by panuganti** [dbaq/cordova-plugin-contacts-phone-numbers#30]
I use Angular2/Ionic-v2 with typescript. Please add a corresponding typescript definition file.

**Comment by dbaq** [comment]
hey @panuganti, I added a TS definition file. Let me know if it works for you.

**Comment by panuganti** [comment]
Thanks. I'll check tomorrow and let you know.

**Comment by panuganti** [comment]
hey @dbaq, I'm trying to use it in my ionic-v2 (uses Angular2) app. I installed the plugin and attempted to use it in one of my page by import {ContactsPhoneNumbers, Contact} from '<path_to_.d.ts file>'; (I first added export to all the interfaces in the .d.ts file.

then, in my code, when I tried,
 this.platform.ready().then(() => {
                navigator.contactsPhoneNumbers.list(contacts => {
                    console.log(contacts.length + ' contacts found');
               }
}

I get an error, "Property 'contactsPhoneNumbers' does not exist on type 'Navigator'"

Two ques:
a) Can you please add to documentation how to work with ionic-v2 app with this plugin
b) Any suggestion on how to resolve this error ? Do I need to add the .js script to my index.html file ?

**Comment by dbaq** [comment]
Hey @panuganti,

I am no TS expert yet, I need to dig into ionic v2. I will try to take a look at it quickly.

**Comment by MarinoRaul** [comment]
What's up about this issue? Any solution? 

I have the same problem!

Thanks!

**Comment by dbaq** [comment]
Feel free to contribute to this issue. I have no time right now to fix this one.

**Comment by MarinoRaul** [comment]
I solved with:

declare var navigator: any in my typescript file!

Thanks!

**Comment by deounix** [comment]
@MarinoRaul Can u explain how did you solve this? any simple example ?

**Comment by dbaq** [comment]
Please refer to #59 and the readme. Thanks.
