### ISSUE TITLE
Contact Photo

### ISSUE THREAD

**Issue by calanti** [dbaq/cordova-plugin-contacts-phone-numbers#32]
Firstly I would like to say thank you so much for your work here. I have been struggling for a while with stupidly long load times on my app, and trading out the official contacts plugin for your's has dropped my loading time from 10 seconds to less than 1, it's unbelievable, well done.

Secondly, I apologise as this question has been discussed already in issue #11 , so I would just like to know if you will be including thumbnail URL's for Android and iOS in the future?

Regards

**Comment by dbaq** [comment]
Hey @calanti, 

I am glad to hear you got your performance issues solved with this plugin.

I don't have a lot of bandwidth to work on this plugin right now but I will try to take a look at it during the next few days.

I'll keep you posted.

**Comment by peterchibunna** [comment]
I have added the contact thumbnail feature; but I need someone to test it for performance issues. I can do a PR if requested.

**Comment by dbaq** [comment]
hey @peterchibunna, any contribution is welcome. Please open a PR and do some performance testing (especially on android).

**Comment by peterchibunna** [comment]
I think we can close this. It didn't affect performance at all.

**Comment by dbaq** [comment]
hey @peterchibunna, thanks for bumping this thread, let's move the discussion back to #44

**Comment by dbaq** [comment]
Closing this one since #44 has been merged. Thanks @peterchibunna 🍻

**Comment by dbaq** [comment]
I released a new version on npm https://www.npmjs.com/package/cordova-plugin-contacts-phonenumbers (v0.0.9)

**Comment by peterchibunna** [comment]
Thanks. Please do not forget to note that the thumbnail is only available on Android at the moment.
