### ISSUE TITLE
How delete or update contact?

### ISSUE THREAD

**Issue by crazyshock** [dbaq/cordova-plugin-contacts-phone-numbers#33]
Hello,

How do I update a contact?
Or delete only a mobile phone number if the user has 2 numbers.

Thankx!

**Comment by dbaq** [comment]
Hello @crazyshock,

This plugin is a efficient read only plugin. If you need to create/update/delete contacts, please use this library https://github.com/apache/cordova-plugin-contacts.

Cheers
