### ISSUE TITLE
Expose device data to application

### ISSUE THREAD

**Issue by georgechapman** [dbaq/cordova-plugin-contacts-phone-numbers#39]
Hi,

I need some help with accessing the data... I am trying to expose the data retrieved from the device to my application but without success. I am using the following code which executes fine; writing a list of the normalized numbers and then on completion of this writing an array of these number to the console.

```
        var success = function(contacts) {
          var numbersList = [];
          for(var i = 0; i < contacts.length; i++) {
            for(var j = 0; j < contacts[i].phoneNumbers.length; j++) {
              var phone = contacts[i].phoneNumbers[j];
              if (phone.type === 'MOBILE' && contacts[i].displayName != null){
                console.log("=> " + phone.normalizedNumber);
                numbersList.push(phone.normalizedNumber);
              }
            }
          }
          console.log(numbersList);
        }
        var failure = function() {
          console.log('error');
        }
        navigator.contactsPhoneNumbers.list(success, failure);
```

What i need is to pass this array to my application however it is not visible form outside of the success function. likewise if i try and pass a predefined variable (`numberList:any = [];`) into the success function and try to populate it there ( `this.numbersList.push(phone.normalizedNumber);` ) I get the error.

> TypeError: Cannot read property 'numbersList' of null

Any help would be greatly appreciated.

Cheers.

**Comment by DilipNikam** [comment]
Same problem I am also facing.... If you have any solution pls let me know..... thanks...

**Comment by dbaq** [comment]
hey guys,

here is a piece of code that I wrote with TypeScript:

```
export class ContactPage {
  contacts: Array<any> = [];
  groupedContacts: Array<any> = [];


  fetchContacts(cb) {
    let loader = this.loadingCtrl.create({content: "Retrieving contacts..."});
    this.platform.ready().then((readySource) => {
      loader.present();
      this.isFetching = true;
      let that = this;
      navigator.contactsPhoneNumbers.list(function(contacts) {
        console.log(contacts.length + ' contacts found');
        for(var i = 0; i < contacts.length; i++) {
           console.log(contacts[i].id + " - " + contacts[i].displayName);
           for(var j = 0; j < contacts[i].phoneNumbers.length; j++) {
              var phone = contacts[i].phoneNumbers[j];
              console.log("===> " + phone.type + "  " + phone.number + " (" + phone.normalizedNumber+ ")");
              that.contacts.push({
                name: contacts[i].displayName,
                number: phone.normalizedNumber,
                invited: false
              });
           }
        }
        that.groupContacts(that.contacts);
        that.isFetching = false;
        loader.dismiss();
        cb && cb();
      }, function(error) {
        console.error(error);
        that.isFetching = false;
        loader.dismiss();
      });
    });
  }

  groupContacts(contacts){
    this.groupedContacts = []; // init grouped list
    // sort all contacts by display name
    let sortedContacts = contacts.sort(function(a,b) {
      var x = a.name.toLowerCase();
      var y = b.name.toLowerCase();
      return x < y ? -1 : x > y ? 1 : 0;
    });
    let currentLetter = false;
    let currentContacts = [];
    // assign each contact to a group
    sortedContacts.forEach((value, index) => {
        if(value.name.charAt(0) != currentLetter){
            currentLetter = value.name.charAt(0);
            let newGroup = {
                letter: currentLetter,
                contacts: []
            };
            currentContacts = newGroup.contacts;
            this.groupedContacts.push(newGroup);
        } 
        currentContacts.push(value);
    });
   }
}

```

**Comment by DilipNikam** [comment]
Thanks for the quick response.Will implement and check

**Comment by DilipNikam** [comment]
I have figure out how to get contacts list in page variables after lots of digging and help from @dbaq . Thanks for your help.

First you need to create Observable method as below.

    getContacts() : Observable<any> {
     return Observable.create(observer => {
         return navigator.contactsPhoneNumbers.list(function(contacts) {
            observer.next(contacts);
            observer.complete();
          }, function(error) {
                console.error(error);
          });
      });

Convert this Observable into the promise as below. Inside this method I am doing the sorting also.

    this.getContacts()
            .map(contacts => {
              this.contactlist = contacts.sort((leftSide, rightSide): number => {
                    var leftName = this.convertToString(leftSide.displayName).toLowerCase();
                    var rightName = this.convertToString(rightSide.displayName).toLowerCase();
                    if(leftName < rightName) return -1;
                    if(leftName > rightName) return 1;
                    return 0;
                });
            })
            .toPromise()
            .catch(err => {
              console.error(err);
            });

convertToString method - This will handle null exception in case if any contact without name exists.

    convertToString(inputValue){
    if(inputValue == null)
      return '';
    else
     return inputValue;
    }
