### ISSUE TITLE
How to use this plugin in iOnic2 ?

### ISSUE THREAD

**Issue by DilipNikam** [dbaq/cordova-plugin-contacts-phone-numbers#40]
I am new to iOnic 2. I have followed your instruction & trying to use this plugin in my project but not succeeded. Facing below two errors.

If use **import {ContactsPhoneNumbers, Contact} from 'com.dbaq.cordova.contactsPhoneNumbers'**
1) Cannot find module "com.dbaq.cordova.contactsPhoneNumbers"

if use **declare var contactsPhoneNumbers:any;**
2) Uncaught (in promise): ReferenceError: contactsPhoneNumbers is not defined

request you to please guide me for the same. If you can provide sample project its really appreciate...

Thanks in Advance....

**Comment by dbaq** [comment]
please see #39

**Comment by DilipNikam** [comment]
Thanks for the quick response.Will implement and check

**Comment by anakaku1623-cloud** [comment]
#39
