### ISSUE TITLE
PLUGIN NOT WORKING

### ISSUE THREAD

**Issue by AbrahamOdoi** [dbaq/cordova-plugin-contacts-phone-numbers#41]
Hello team

I have been trying ti get the below plugin to work for months without any success. i copied the exxact example from the page https://www.npmjs.com/package/cordova-plugin-contacts-phonenumbers and it still doesnt work.

Plugin:
<plugin name="cordova-plugin-contacts-phonenumbers" />

Please help me out

**Comment by dbaq** [comment]
hey @AbrahamOdoi,

do you have any errors/stacktrace/code to share?

**Comment by AbrahamOdoi** [comment]
https://github.com/AbrahamOdoi/mecamera.git

Above is my git repository. I dont have any error.

	document.getElementById("getContact").onclick = function() {
			navigator.contactsPhoneNumbers.list(function(contacts) {
				alert(contacts.length + ' contacts found');
				for (var i = 0; i < contacts.length; i++) {
					// console.log(contacts[i].id + " - " + contacts[i].displayName);
					for (var j = 0; j < contacts[i].phoneNumbers.length; j++) {
						var phone = contacts[i].phoneNumbers[j];
						console.log("===> " + phone.type + "  " + phone.number + " (" + phone.normalizedNumber + ")");
						alert(phone);
					}
				}
			}, function(error) {
				alert(error);
				console.error(error);
			});
		}

**Comment by dbaq** [comment]
Are you waiting that cordova init event is fired?

**Comment by AbrahamOdoi** [comment]
nope i am actually just executing on device ready

**Comment by AbrahamOdoi** [comment]
I believe that should trigger the cordova init. Please have you been able to go through the code

**Comment by dbaq** [comment]
Hey @AbrahamOdoi, your code looks fine to me. Can you try to add two console.log around this line https://github.com/dbaq/cordova-plugin-contacts-phone-numbers/blob/master/www/contactsPhoneNumbers.js#L38 (in your plugin folder) and check if you see one of these logs. If you don't that means that the plugin is never called and the issue is somewhere in your code.

**Comment by AbrahamOdoi** [comment]
Do you have a skype id i can contact you on.

**Comment by AbrahamOdoi** [comment]
@dbaq I am a bit confused the code you shared isn't familiar

**Comment by dbaq** [comment]
hello @AbrahamOdoi let's keep the discussion here. Can you please share the full structure of your directory, you should have a directory for cordova where you can find this file (`contactsPhoneNumbers.js`)

**Comment by AbrahamOdoi** [comment]
I have included the contactsPhoneNumbers.js but still same. is there a sample project i can make use of
