### ISSUE TITLE
got error with last version of cordova-plugin-contacts

### ISSUE THREAD

**Issue by MarinoRaul** [dbaq/cordova-plugin-contacts-phone-numbers#43]
typescript: plugins/com.dbaq.cordova.contactsPhoneNumbers/www/ContactsPhoneNumbers.d.ts, line: 18 
            Interface 'Contact' incorrectly extends interface 'ContactProperties'. Types of property 'phoneNumbers' are 
            incompatible. Type 'ContactPhoneNumber[]' is not assignable to type 'ContactField[]'. Type 
            'ContactPhoneNumber' is not assignable to type 'ContactField'. Property 'type' is optional in type 
            'ContactPhoneNumber' but required in type 'ContactField'. 

      L18:  interface Contact {
      L19:      /** A globally unique identifier. */

[16:33:40]  typescript: plugins/cordova-plugin-contacts/types/index.d.ts, line: 140 
            Subsequent variable declarations must have the same type. Variable 'Contact' must be of type 'new (id?: 
            string, firstName?: string, LastName?: string, displayName?: string, phoneNumbers?: Con...', but here has 
            type 'new (id?: string, displayName?: string, name?: ContactName, nickname?: string, phoneNumbers?: Con...'. 

     L139:  emails?: ContactField[],
     L140:  addresses?: ContactAddress[],
     L141:  ims?: ContactField[],

**Comment by dbaq** [comment]
hello @MarinoRaul,

The typescript definition was an experimentation and I believe it is not working properly. I don't have time currently to fix it. I do accept PR if you want to participate to this project.

Cheers,

**Comment by dbaq** [comment]
Closing this one in favor of #30.
