### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by kodeine** [dbaq/cordova-plugin-contacts-phone-numbers#46]
```
$ cordova plugin add cordova-plugin-contacts-phonenumbers
Error: Failed to fetch plugin git+https://github.com/dbaq/cordova-plugin-contacts-phone-numbers.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by kodeine** [comment]
no one?

**Comment by kodeine** [comment]
```
Failed to restore plugin "com.dbaq.cordova.contactsPhoneNumbers" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin com.dbaq.cordova.contactsPhoneNumbers@https://github.com/dbaq/cordova-plugin-contacts-phone-numbers.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module
```

**Comment by seniorwebdev** [comment]
Not sure, I have the same problem on Mac, but when I build android all is fine. Maybe this related by node/cordova/ionic/npm versions?

Android:
npm: 4.2.0
node: 7.10.1
cordova: 7.0.1
ionic: 3.5.0

MAC:
npm:5.3.0
node:8.2.1
cordova:7.0.1
ionic:3.9.2

Maybe some one know what could be a problem in fetching plugin?

**Comment by dbaq** [comment]
interesting, i am going to merge the open PR to see if that helps.

**Comment by kodeine** [comment]
@dbaq it does help. :)

**Comment by dbaq** [comment]
thanks @kodeine for your contribution 👍

**Comment by asifmehmood91** [comment]
Having same problem while installing this plugin

**Comment by asifmehmood91** [comment]
Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "com.dbaq.cordova.contactsPhoneNumbers" via npm Failed to fetch plugin com.dbaq.cordova.contactsPhoneNumbers via registry. Probably this is either a connection problem, or plugin spec is incorrect. Check your connection and plugin name/version/URL. Error: Not found : com.dbaq.cordova.contactsPhoneNumbers - You can fix this here

**Comment by asifmehmood91** [comment]
`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "com.dbaq.cordova.contactsPhoneNumbers" via npm Failed to fetch plugin com.dbaq.cordova.contactsPhoneNumbers via registry. Probably this is either a connection problem, or plugin spec is incorrect. Check your connection and plugin name/version/URL. Error: Not found : com.dbaq.cordova.contactsPhoneNumbers - You can fix this here`
