### ISSUE TITLE
fix for installation issue not released

### ISSUE THREAD

**Issue by MikeVerhees** [dbaq/cordova-plugin-contacts-phone-numbers#50]
I've encountered an issue while using the latest release version that is already fixed in #47 
Would be great if a new release is made that supports this so we can use 
`cordova plugin add cordova-plugin-contacts-phonenumbers` again without issues instead of having everyone using the unstable git version or forking.

**Comment by dbaq** [comment]
Ooops, thanks for the heads up! I published a new version on npm (0.0.10) => https://www.npmjs.com/package/cordova-plugin-contacts-phonenumbers
