### ISSUE TITLE
App crashes when method is called — iOS 11.3

### ISSUE THREAD

**Issue by DamilolaJegede** [dbaq/cordova-plugin-contacts-phone-numbers#51]
Please check that this plugin works with iOS 11.3. As soon as the plugin is called, the app crashes. Please help check.

Thanks a million.

**Comment by dbaq** [comment]
Can you share the xcode stack trace? Thank you

**Comment by msarsha** [comment]
Same issue here, app crashes when invoking the `list` function (it does exists if I console.log the function)

**Comment by Karthik-king** [comment]
Yeah. I also have the same issue here.
Shows message as "Message from debugger: Terminated due to memory issue"


![rsz_43003841-744eacb0-8c4b-11e8-9d07-53989b4baa31](https://user-images.githubusercontent.com/41477999/43004185-9edb077a-8c4c-11e8-80e8-7aacc16cbe73.jpg)

 
Thanks in advance.

**Comment by Purushoth-ltr** [comment]
Any updates regarding this issue?

**Comment by dbaq** [comment]
hey @Karthik-king, can you please detail your solution? I am confused how the memory issue disappeared. 

Does anyone else have a stacktrace to share?

**Comment by Lomski** [comment]
I have the same issue in my app with iOS 12. It can happen because of ios privacy policy. According to the official plugin documentation:

> Since iOS 10 it's mandatory to provide an usage description in the info.plist if trying to access privacy-sensitive data. When the system prompts the user to allow access, this usage description string will displayed as part of the permission dialog box, **but if you didn't provide the usage description, the app will crash before showing the dialog**. Also, Apple will reject apps that access private data but don't provide an usage description.

And their further advice is to add this code to config.xml

```<edit-config target="NSContactsUsageDescription" file="*-Info.plist" mode="merge">
    <string>need contacts access to search friends</string>
</edit-config>```

After that app shows the dialog box and if I allow access all works as expected.

Could you add the appropriate patch to the plugin?

**Comment by dbaq** [comment]
hey @Lomski, do you mind opening a PR? I would really appreciate it. Thanks

**Comment by Lomski** [comment]
Make a pull request [https://github.com/dbaq/cordova-plugin-contacts-phone-numbers/pull/57](url)

**Comment by dbaq** [comment]
`cordova-plugin-contacts-phonenumbers@0.0.12` has been released thanks to @Lomski !
