### ISSUE TITLE
Package dependencies issue

### ISSUE THREAD

**Issue by eranshmil** [dbaq/cordova-plugin-contacts-phone-numbers#52]
After I install the plugin everything fine.
But each time I run a Cordova command (e.g running on a device), it adds a new package to the dependencies: com.dbaq.cordova.contactsPhoneNumbers
So, I end with two dependencies related to this plugin:
cordova-plugin-contacts-phonenumbers and com.dbaq.cordova.contactsPhoneNumbers

To install some other stuff using npm, I had to remove com.dbaq.cordova.contactsPhoneNumbers directly from the file, so I won't get a 404 error.

**Comment by dbaq** [comment]
Fixed via 93506d4ad97ae80582399de2d7656c745b38140e.
