### ISSUE TITLE
unable to fetch this plugin during installation 

### ISSUE THREAD

**Issue by asifmehmood91** [dbaq/cordova-plugin-contacts-phone-numbers#55]
`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "com.dbaq.cordova.contactsPhoneNumbers" via npm Failed to fetch plugin com.dbaq.cordova.contactsPhoneNumbers via registry. Probably this is either a connection problem, or plugin spec is incorrect. Check your connection and plugin name/version/URL. Error: Not found : com.dbaq.cordova.contactsPhoneNumbers - You can fix this here`
unable to fetch this plugin during installation on [phonegap](https://build.phonegap.com)

**Comment by dbaq** [comment]
hey @asifmehmood91 

Install the plugin via:

```cordova plugin add https://github.com/dbaq/cordova-plugin-contacts-phone-numbers.git```

**Comment by asifmehmood91** [comment]
![sketch](https://user-images.githubusercontent.com/14163289/41919783-c1805672-7978-11e8-9f59-b1ebbef82860.png)
here is the error while installing through `phonegap plugin add https://github.com/dbaq/cordova-plugin-contacts-phone-numbers.git`

**Comment by dbaq** [comment]
Should be fixed via 93506d4ad97ae80582399de2d7656c745b38140e
