### ISSUE TITLE
App Crash: Android 5.1

### ISSUE THREAD

**Issue by kodeine** [dbaq/cordova-plugin-contacts-phone-numbers#56]
<img width="955" alt="screen shot 2018-09-28 at 7 03 06 pm" src="https://user-images.githubusercontent.com/8620059/46238387-29737580-c351-11e8-855a-5ec3fa94130c.png">

**Comment by dbaq** [comment]
hey @kodeine,

could it be a permission issue? this code https://github.com/dbaq/cordova-plugin-contacts-phone-numbers/blob/master/src/android/ContactsManager.java#L98-L102 returns null and it should not.

**Comment by dbaq** [comment]
Closing since no response.
