### ISSUE TITLE
IOS: Is NSContactsUsageDescription requirement applicable to this plugin?

### ISSUE THREAD

**Issue by vicatcu** [dbaq/cordova-plugin-contacts-phone-numbers#61]
The cordova-plugin-contacts repository has the section excerpted below in the README. Does it also apply to this plugin? if so, maybe it should be duplicated in the README. If not, it should probably also be stated why not. I suspect it does.

> iOS Quirks
> Since iOS 10 it's mandatory to provide an usage description in the info.plist if trying to access privacy-sensitive data. When the system prompts the user to allow access, this usage description string will displayed as part of the permission dialog box, but if you didn't provide the usage description, the app will crash before showing the dialog. Also, Apple will reject apps that access private data but don't provide an usage description.
>
> This plugins requires the following usage description:
>
> NSContactsUsageDescription describes the reason that the app accesses the user's contacts.
> To add this entry into the info.plist, you can use the edit-config tag in the config.xml like this:
> 
> ```
> <edit-config target="NSContactsUsageDescription" file="*-Info.plist" mode="merge">
>    <string>need contacts access to search friends</string>
> </edit-config>
> ```

**Comment by dbaq** [comment]
You are correct. Do you mind opening a PR?

**Comment by vicatcu** [comment]
Can do :+1:

**Comment by dbaq** [comment]
Thanks, Victor. I really appreciate it! 🍻
