### ISSUE TITLE
Missing Contacts

### ISSUE THREAD

**Issue by elzahaby** [dbaq/cordova-plugin-contacts-phone-numbers#63]
For some Reason, some Contacts on IOS are not in the list. I tried to manipulate them but the simply dont apear.

**Comment by dbaq** [comment]
Hi @elzahaby,

Can you please provide more information? Can you share the iOS version, Xcode logs, and a concrete reproducible example?

Thank you

**Comment by elzahaby** [comment]
Hi, I am sorry I just figured out what was wrong, using Ajax Request to send data to the server has some kind of Maximum, by spliting the contacts list every 200 entries i was able to send the whole of it.
