### ISSUE TITLE
Display name in iOS 

### ISSUE THREAD

**Issue by ranaesam** [dbaq/cordova-plugin-contacts-phone-numbers#8]
Hi ,

display name returned a space when it's empty , and i don't want to remove the empty space to some function because may i have a contact with one character name .

thanks,
rana

**Comment by dbaq** [comment]
Hey @ranaesam,

are you sure about that? here is the json returned:

```
{
    "firstName": "",
    "id": "10",
    "lastName": "",
    "displayName": "",
    "phoneNumbers": [{
        "number": "1 (586) 649-8332",
        "normalizedNumber": "1 (586) 649-8332",
        "type": "HOME"
    }]
}
```

There is no space. Could you dump an example please?
